### PR TITLE
Add extension in contact

### PR DESCRIPTION
**Pull request by powerpbx**
Add `extension-in-contact` feature to gateways setting.  
https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Gateway+Authentication+Params

By default it is `false`.  Some sip providers require it to be `true`.   

For example, in order to use Telnyx.com AnchorSite manually set to a specific site, for outbound calls, when using user/pass authentication, this must be set to `true`.

NOTE: `freeswitch_form.php` is shown as all new because git doesn't appear to be detecting just the one section that was updated.  The file is exactly the same as before with the addition of the following.

```
array (
	gettext ( 'Extension-In-Contact' ),
	array (
		'name' => 'extension-in-contact',
		'class' => 'add_settings' 
	),
	'SELECT',
	'',
	'',
	'tOOL TIP',
	'',
	'',
	'',
	'',
	'set_sip_config_option' 
),
```
On line [1130](https://github.com/powerpbx/ASTPP-1/blob/c0672275d9ba7870aff3df8213ccc2e8f13db924/web_interface/astpp/application/modules/freeswitch/libraries/freeswitch_form.php#L1130)

The `messages.mo` language binary files were updated using this generator.
https://po2mo.net/

### CODE REVIEW

**Comment by devangn** [comment]
@powerpbx Thanks for the PR. We have this config change in mind from the google group thread '[New provider registration](https://groups.google.com/d/msgid/astpp/f85df99f-80ac-418a-88c3-cdbf5d71d6bd%40googlegroups.com?utm_medium=email&utm_source=footer)'
About extension-in-contact config, we cannot consider it as 'Basic Configuration.' We'll add it under 'Optional Information.'
Other then that currently the class you have used for toggle drop down is setting default value to 'True' and we are using terminal based .po to .mo conversion tool. So we are closing this PR but will add commit for 'extension-in-contact' in existing v3.6 branch soon.
Thanks again.

**Comment by powerpbx** [comment]
Default is being set to false not true.  So it does not change existing default.  I can't use my SIP trunk provider without this change so when do you plan to add this?   Otherwise I may have to use my own fork.  When do you plan to add this feature?  

I disagree that it is not Basic Configuration.  It is listed on the freeswitch website under standard gateway settings along with the other configurations you have in basic config.

**Comment by devangn** [comment]
#434 is new PR, you can use from there or we'll merge it soon.
We agree with you about its just a new gateway param.
Feature will be added, because we know it is useful.

**Comment by devangn** [comment]
#434 PR merged.

**Pull request closed without merging**
