### PR TITLE
fix for PHP v7.4

### PR DESCRIPTION
**Pull request by sdwru**
This fixes PHP v7.4 not working.  Tested on Debian 11.

### CODE REVIEW

**Comment by powerpbx** [comment]
It is backwards compatible so it still works the same as before on PHP v7.3.  Tested on Debian 11.

**Comment by sdwru** [comment]
It is backwards compatible so it still works the same as before on PHP v7.3.  Tested on Debian 11.

**Comment by HP371** [comment]
@sdwru , we have veirfied this PR and it's seems working with php7.4.
As you mention in above comment **This fixes PHP v7.4 not working. Tested on Debian 11.**
Is there any specific reason else we can merge this PR in main repo, please confirm.

Also for **geoip_country_name_by_name** issue related geoip we need to install **php7.4-geoip** package

**Comment by sdwru** [comment]
> @sdwru , we have veirfied this PR and it's seems working with php7.4. As you mention in above comment **This fixes PHP v7.4 not working. Tested on Debian 11.** Is there any specific reason else we can merge this PR in main repo, please confirm.
> 
> Also for **geoip_country_name_by_name** issue related geoip we need to install **php7.4-geoip** package

The official ASTPP install script includes `php7.x-geoip`, so that package should also be installed on 7.4.

**Comment by ScIT-Raphael** [comment]
May I ask why this isnt merged yet?

**Review by devangn — APPROVED** [review]

**Pull request merged**
