### PR TITLE
Current WIP

### PR DESCRIPTION
**Pull request by xrobau**
This is the 3.6 branch with all the current fixes applied, APART from the ones I mentioned in glitter.

Also:
* Remove all PHP short open tags
* Fixes all PHP warnings, so it can be run with php 7
* Much better error reporting, and all error reporting turned ON (so hopefully it never gets as buggy as it was again!)
* Support for MySQL 5.7
** Note this uses 01-01-1980 as a replacement for the (invalid) 00-00-0000 datestamp. The better way to do that is to allow NULL datestamps, which is partially done

This would be a good starting point for 3.7!

### CODE REVIEW

**Comment by xrobau** [comment]
Most of the conflicts are either ^M repairs, or short-php-opens.  I haven't looked too hard. Also, I haven't even checked if this code works, this was just getting my branch up to date with yours. There may be more commits coming.

**Comment by smrdoshi** [comment]
Hi @xrobau 

Thanks for the updates. 
Merge conflicts are there, are you planning to add more commits on this branch?

**Comment by xrobau** [comment]
The merge conflicts aren't really fixable, if you look through them, because they're differences in the entire file (eg, remove ^M's) or different ways of doing things. You get to pick what you want to merge 8)

Github has a surprisingly good 'resolve conflicts' button.

**Comment by smrdoshi** [comment]
Alright. I will look at that.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by xrobau** [comment]
I'm not going to persevere with this pull request, as it's just getting more and more stale. Plus commits like https://github.com/iNextrix/ASTPP/commit/309a35a5f1bc2a8aa4fb44deff1cbf3103669528 where one file was randomly placed inside another (breaking all CDRs) really disheartens me.

**Comment by smrdoshi** [comment]
Hi Rob,

That was unfortunate bug and I hope there will not be any other.

How would you like to keep your branch running?

**Pull request closed without merging**
