### PR TITLE
V3.6

### PR DESCRIPTION
**Pull request by igorolhovskiy**
Restore search position on accounts search and added search on codes when adding codes list to packages.
In 2 separate commits.

### CODE REVIEW

**Comment by smrdoshi** [comment]
Hi @samael33 
I have question for "Restore search position on accounts search ". 

Can you please explain what exactly this feature will do?

**Comment by igorolhovskiy** [comment]
Idea is when you're searching in Accounts List (Customer - Accounts) and enter to edit one of them, when you back to Accounts List it saves search results.

**Comment by smrdoshi** [comment]
We are using same search session variables for other modules such as admin and reseller. So I think when you will search in customer and then go to admin, it will also give you filtered data. Same thing applicable on reseller. 

That might confuse the user as they will see less data and might thing that system have an issue. 

Please confirm.

**Comment by igorolhovskiy** [comment]
Need to test against reseller. But idea is more comfortable to work with search results.

**Comment by smrdoshi** [comment]
Ok i got the idea but found impact on other module. Please let me know the
outcome of your testing.

**Pull request closed without merging**
