### PR TITLE
Issue 142

### PR DESCRIPTION
**Pull request by countrdd**
Adding option to import termination rates using a column mapper

### CODE REVIEW

**Comment by smrdoshi** [comment]
@countrdd We have checked and found the issues. We have reported all the issues in, 
https://github.com/iNextrix/ASTPP/issues/149

**Comment by countrdd** [comment]
Updated.

**Comment by dev-astpp** [comment]
@countrdd  We have checked fixed issues and give update with new found issues. We have reported all the issues in, 
#149

**Comment by countrdd** [comment]
I must not be pusing this write, because it is fine on my systems….for all the erros you said.hmmmm

**Comment by smrdoshi** [comment]
@countrdd, I am sure it must be working perfect in your setup with proper data. While we are getting contribution from someone, that is our duty to verify the code and features with proper and improper data and once everything fine release it under the open source version. So that community not get buggy contributions and they can adopt new changes without hassle.

So far the feature which you have implemented will really be going to useful to all admins as they will no longer require to format the csvs to import the termination rates.

**Comment by countrdd** [comment]
I agree, I should have been more clear, the format changes for the screen (i.e. html) looked like what you have pointed out, and I fixed that and for some reason I am cannot seem to push that up…

I am really looking forward to getting these in and figuring out what I am doing wrong with the pull request, that way I can contribute more.

Dusty

**Comment by countrdd** [comment]
See here is where it looks ok

**Comment by countrdd** [comment]
Sorry, Got busy. I think everything is there, just need to know if I need to do anything else.

**Pull request closed without merging**
